# Generated by Django 3.1.3 on 2020-11-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='id_medico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Medico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
