# Generated by Django 3.1.3 on 2020-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20201129_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='historial',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
