# Generated by Django 3.1.3 on 2020-11-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_pacientes_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='observacion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
