# Generated by Django 3.1.3 on 2020-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='armazon',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=1, null=True),
        ),
    ]
