# Generated by Django 3.1.3 on 2020-11-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201130_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='armazon',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='cercania',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='lado',
        ),
        migrations.AddField(
            model_name='pedidosdet',
            name='armazon',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdet',
            name='cercania',
            field=models.CharField(choices=[('L', 'Lejos'), ('C', 'Cerca')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdet',
            name='clasificacion',
            field=models.CharField(choices=[('L', 'Lentes'), ('O', 'Otros')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdet',
            name='lado',
            field=models.CharField(choices=[('I', 'Izquierda'), ('D', 'Derecha')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='clasificacion',
            field=models.CharField(choices=[('L', 'Lentes'), ('O', 'Otros')], max_length=1, null=True),
        ),
    ]
