# Generated by Django 3.1.3 on 2020-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20201130_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosdet',
            name='armazon',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosdet',
            name='cercania',
            field=models.CharField(choices=[('L', 'Lejos'), ('C', 'Cerca'), ('N', 'Ninguno')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedidosdet',
            name='lado',
            field=models.CharField(choices=[('I', 'Izquierda'), ('D', 'Derecha'), ('N', 'Ninguno')], default='N', max_length=1, null=True),
        ),
    ]
