# Generated by Django 3.1.3 on 2020-12-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20201130_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoscab',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidosdet',
            name='cantidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidosdet',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.productos'),
        ),
        migrations.AlterField(
            model_name='pedidosdet',
            name='unitario',
            field=models.FloatField(null=True),
        ),
    ]
