# Generated by Django 3.1.3 on 2020-12-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20201129_2325'),
        ('ventas', '0005_auto_20201130_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoscab',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes'),
        ),
    ]
